# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='dashboard.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='dashboard.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorToParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitortoparty', to='dashboard.Invoice')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitortoparty_set', to='dashboard.Party')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitortoparty_set', to='dashboard.Visitor')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='visitors',
            field=models.ManyToManyField(related_name='parties', through='dashboard.VisitorToParty', to='dashboard.Visitor'),
        ),
    ]
